"""crear tablas para servicios y tecnicos

Revision ID: 1cbb360aee58
Revises: d1cc514a62d2
Create Date: 2025-10-27 23:16:37.277104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1cbb360aee58'
down_revision: Union[str, Sequence[str], None] = 'd1cc514a62d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicios',
    sa.Column('id_ser', sa.Integer(), nullable=False),
    sa.Column('nombre_ser', sa.String(length=255), nullable=False),
    sa.Column('descripcion_ser', sa.String(length=255), nullable=False),
    sa.Column('precio_ser', sa.String(length=255), nullable=False),
    sa.Column('created_at_ser', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_ser', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_ser', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_ser', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id_ser')
    )
    op.create_table('tecnicos',
    sa.Column('id_tec', sa.Integer(), nullable=False),
    sa.Column('nombre_tec', sa.String(length=255), nullable=False),
    sa.Column('apellido_paterno_tec', sa.String(length=255), nullable=False),
    sa.Column('apellido_materno_tec', sa.String(length=255), nullable=False),
    sa.Column('telefono_tec', sa.String(length=20), nullable=True),
    sa.Column('fecha_ingreso_tec', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_tec', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_tec', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_tec', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_tec', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id_tec')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tecnicos')
    op.drop_table('servicios')
    # ### end Alembic commands ###
