"""crear tabla clientes

Revision ID: b6b63508df1d
Revises: 
Create Date: 2025-10-27 20:20:03.063728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b6b63508df1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cli', sa.Integer(), nullable=False),
    sa.Column('nombre_cli', sa.String(length=255), nullable=False),
    sa.Column('apellido_paterno_cli', sa.String(length=255), nullable=False),
    sa.Column('apellido_materno_cli', sa.String(length=255), nullable=False),
    sa.Column('telefono_cli', sa.String(length=20), nullable=True),
    sa.Column('created_at_cli', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_cli', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_cli', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_cli', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id_cli')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
