"""crear tablas para equipos

Revision ID: d1cc514a62d2
Revises: b6b63508df1d
Create Date: 2025-10-27 22:16:39.971346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1cc514a62d2'
down_revision: Union[str, Sequence[str], None] = 'b6b63508df1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_equipo',
    sa.Column('id_teq', sa.Integer(), nullable=False),
    sa.Column('nombre_teq', sa.String(length=255), nullable=False),
    sa.Column('descripcion_teq', sa.String(length=255), nullable=False),
    sa.Column('created_at_teq', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_teq', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_teq', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_teq', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id_teq')
    )
    op.create_table('equipos',
    sa.Column('id_equ', sa.Integer(), nullable=False),
    sa.Column('marca_equ', sa.String(length=255), nullable=False),
    sa.Column('modelo_equ', sa.String(length=255), nullable=False),
    sa.Column('id_tipo_equipo_equ', sa.Integer(), nullable=True),
    sa.Column('id_dueno_equ', sa.Integer(), nullable=True),
    sa.Column('estado_equ', sa.String(length=255), nullable=True),
    sa.Column('created_at_cli', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_cli', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_cli', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_cli', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id_dueno_equ'], ['clientes.id_cli'], ),
    sa.ForeignKeyConstraint(['id_tipo_equipo_equ'], ['tipos_equipo.id_teq'], ),
    sa.PrimaryKeyConstraint('id_equ')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipos')
    op.drop_table('tipos_equipo')
    # ### end Alembic commands ###
