"""crear enum para trabajos

Revision ID: f025ddbd0b7d
Revises: f7c943f0315b
Create Date: 2025-10-28 02:19:47.739962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f025ddbd0b7d'
down_revision: Union[str, Sequence[str], None] = 'f7c943f0315b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trabajos', 'estado_tra',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trabajos', 'estado_tra',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
