"""primer migration con conexion a supabase

Revision ID: f775b3b76ca4
Revises: 
Create Date: 2026-01-19 05:56:26.244303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f775b3b76ca4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cli', sa.Integer(), nullable=False),
    sa.Column('nombre_cli', sa.String(length=255), nullable=False),
    sa.Column('apellido_paterno_cli', sa.String(length=255), nullable=False),
    sa.Column('apellido_materno_cli', sa.String(length=255), nullable=False),
    sa.Column('telefono_cli', sa.String(length=20), nullable=True),
    sa.Column('created_at_cli', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_cli', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_cli', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_cli', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id_cli')
    )
    op.create_table('servicios',
    sa.Column('id_ser', sa.Integer(), nullable=False),
    sa.Column('nombre_ser', sa.String(length=255), nullable=False),
    sa.Column('descripcion_ser', sa.String(length=255), nullable=False),
    sa.Column('precio_ser', sa.String(length=255), nullable=False),
    sa.Column('created_at_ser', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_ser', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_ser', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_ser', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id_ser')
    )
    op.create_table('tecnicos',
    sa.Column('id_tec', sa.Integer(), nullable=False),
    sa.Column('nombre_tec', sa.String(length=255), nullable=False),
    sa.Column('apellido_paterno_tec', sa.String(length=255), nullable=False),
    sa.Column('apellido_materno_tec', sa.String(length=255), nullable=False),
    sa.Column('telefono_tec', sa.String(length=20), nullable=True),
    sa.Column('fecha_ingreso_tec', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_tec', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_tec', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_tec', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_tec', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id_tec')
    )
    op.create_table('tipos_equipo',
    sa.Column('id_teq', sa.Integer(), nullable=False),
    sa.Column('nombre_teq', sa.String(length=255), nullable=False),
    sa.Column('descripcion_teq', sa.String(length=255), nullable=False),
    sa.Column('created_at_teq', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_teq', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_teq', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_teq', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id_teq')
    )
    op.create_table('equipos',
    sa.Column('id_equ', sa.Integer(), nullable=False),
    sa.Column('marca_equ', sa.String(length=255), nullable=False),
    sa.Column('modelo_equ', sa.String(length=255), nullable=False),
    sa.Column('id_tipo_equipo_equ', sa.Integer(), nullable=True),
    sa.Column('id_dueno_equ', sa.Integer(), nullable=True),
    sa.Column('estado_equ', sa.String(length=255), nullable=True),
    sa.Column('created_at_cli', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_cli', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_cli', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_cli', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id_dueno_equ'], ['clientes.id_cli'], ),
    sa.ForeignKeyConstraint(['id_tipo_equipo_equ'], ['tipos_equipo.id_teq'], ),
    sa.PrimaryKeyConstraint('id_equ')
    )
    op.create_table('trabajos',
    sa.Column('id_tra', sa.Integer(), nullable=False),
    sa.Column('descripcion_tra', sa.String(length=255), nullable=False),
    sa.Column('estado_tra', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio_tra', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin_tra', sa.DateTime(timezone=True), nullable=True),
    sa.Column('costo_tra', sa.String(length=255), nullable=False),
    sa.Column('id_tecnico_tra', sa.Integer(), nullable=False),
    sa.Column('created_at_tra', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_tra', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_deleted_tra', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at_tra', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_tecnico_tra'], ['tecnicos.id_tec'], ),
    sa.PrimaryKeyConstraint('id_tra')
    )
    op.create_table('cotizaciones',
    sa.Column('id_cot', sa.Integer(), nullable=False),
    sa.Column('id_cliente_cot', sa.Integer(), nullable=True),
    sa.Column('descripcion_falla_cot', sa.String(length=255), nullable=False),
    sa.Column('diagnostico_cot', sa.String(length=255), nullable=True),
    sa.Column('fecha_expiracion_cot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_tecnico_cot', sa.Integer(), nullable=True),
    sa.Column('estado_cot', sa.String(length=255), nullable=True),
    sa.Column('precio_total_cot', sa.String(length=255), nullable=True),
    sa.Column('id_equipo_cot', sa.Integer(), nullable=True),
    sa.Column('id_trabajo_cot', sa.Integer(), nullable=True),
    sa.Column('created_at_cot', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_cot', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_cot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_cot', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id_cliente_cot'], ['clientes.id_cli'], ),
    sa.ForeignKeyConstraint(['id_equipo_cot'], ['equipos.id_equ'], ),
    sa.ForeignKeyConstraint(['id_tecnico_cot'], ['tecnicos.id_tec'], ),
    sa.ForeignKeyConstraint(['id_trabajo_cot'], ['trabajos.id_tra'], ),
    sa.PrimaryKeyConstraint('id_cot')
    )
    op.create_table('cotizaciones_servicios',
    sa.Column('id_cotizacion', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id_cot'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_ser'], ),
    sa.PrimaryKeyConstraint('id_cotizacion', 'id_servicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotizaciones_servicios')
    op.drop_table('cotizaciones')
    op.drop_table('trabajos')
    op.drop_table('equipos')
    op.drop_table('tipos_equipo')
    op.drop_table('tecnicos')
    op.drop_table('servicios')
    op.drop_table('clientes')
    # ### end Alembic commands ###
