"""crear tablas para cotizaciones y trabajos

Revision ID: f7c943f0315b
Revises: 1cbb360aee58
Create Date: 2025-10-28 02:00:05.824186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7c943f0315b'
down_revision: Union[str, Sequence[str], None] = '1cbb360aee58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajos',
    sa.Column('id_tra', sa.Integer(), nullable=False),
    sa.Column('descripcion_tra', sa.String(length=255), nullable=False),
    sa.Column('estado_tra', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio_tra', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin_tra', sa.DateTime(timezone=True), nullable=True),
    sa.Column('costo_tra', sa.String(length=255), nullable=False),
    sa.Column('id_tecnico_tra', sa.Integer(), nullable=False),
    sa.Column('created_at_tra', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_tra', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_deleted_tra', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at_tra', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_tecnico_tra'], ['tecnicos.id_tec'], ),
    sa.PrimaryKeyConstraint('id_tra')
    )
    op.create_table('cotizaciones',
    sa.Column('id_cot', sa.Integer(), nullable=False),
    sa.Column('id_cliente_cot', sa.Integer(), nullable=True),
    sa.Column('descripcion_falla_cot', sa.String(length=255), nullable=False),
    sa.Column('diagnostico_cot', sa.String(length=255), nullable=True),
    sa.Column('fecha_expiracion_cot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_tecnico_cot', sa.Integer(), nullable=True),
    sa.Column('estado_cot', sa.String(length=255), nullable=True),
    sa.Column('precio_total_cot', sa.String(length=255), nullable=True),
    sa.Column('id_equipo_cot', sa.Integer(), nullable=True),
    sa.Column('id_trabajo_cot', sa.Integer(), nullable=True),
    sa.Column('created_at_cot', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_cot', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at_cot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted_cot', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id_cliente_cot'], ['clientes.id_cli'], ),
    sa.ForeignKeyConstraint(['id_equipo_cot'], ['equipos.id_equ'], ),
    sa.ForeignKeyConstraint(['id_tecnico_cot'], ['tecnicos.id_tec'], ),
    sa.ForeignKeyConstraint(['id_trabajo_cot'], ['trabajos.id_tra'], ),
    sa.PrimaryKeyConstraint('id_cot')
    )
    op.create_table('cotizaciones_servicios',
    sa.Column('id_cotizacion', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id_cot'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_ser'], ),
    sa.PrimaryKeyConstraint('id_cotizacion', 'id_servicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotizaciones_servicios')
    op.drop_table('cotizaciones')
    op.drop_table('trabajos')
    # ### end Alembic commands ###
